[package]
name = "ex09_merge_arrays"
version = "0.1.0"
authors = ["Ahtoms <me@ahtoms.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
